// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKSA078E7GFkymUtvLDhGoMAdmyE0Wdmk',
    appId: '1:258313115527:web:42b8e4aae566f9ec9ca522',
    messagingSenderId: '258313115527',
    projectId: 'fir-example-563475687293',
    authDomain: 'fir-example-563475687293.firebaseapp.com',
    storageBucket: 'fir-example-563475687293.appspot.com',
    measurementId: 'G-TGF04NH3W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIgSGsaC4IpeZAiEajAvIe6bB9X5e2PsI',
    appId: '1:258313115527:android:173c5ac7c7af6ef39ca522',
    messagingSenderId: '258313115527',
    projectId: 'fir-example-563475687293',
    storageBucket: 'fir-example-563475687293.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4tNym4UVCR3A2FEEdQhULAOWWYvO-W-s',
    appId: '1:258313115527:ios:11ba4688fd32922c9ca522',
    messagingSenderId: '258313115527',
    projectId: 'fir-example-563475687293',
    storageBucket: 'fir-example-563475687293.appspot.com',
    iosClientId: '258313115527-he2lhd6n2q5fpeajbcf8ejk4c44jl6p0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4tNym4UVCR3A2FEEdQhULAOWWYvO-W-s',
    appId: '1:258313115527:ios:11ba4688fd32922c9ca522',
    messagingSenderId: '258313115527',
    projectId: 'fir-example-563475687293',
    storageBucket: 'fir-example-563475687293.appspot.com',
    iosClientId: '258313115527-he2lhd6n2q5fpeajbcf8ejk4c44jl6p0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseExample',
  );
}
